import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
//import { Playfair_Display } from "next/font/google";
import { ClientProvidersLayout } from "./ClientProvidersLayout"; 
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const playfair = Playfair_Display({
//   subsets: ["latin"],
//   variable: "--font-playfair",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* This is instead of the font import code block */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet" />
      </head>
      <body
        //className={`${geistSans.variable} ${geistMono.variable} ${playfair.variable} antialiased`}
        className="antialiased"
      >
        <ClientProvidersLayout>{children}</ClientProvidersLayout>
      </body>
    </html>
  );
}
